### ISSUE TITLE
Two Tables on the Same page

### ISSUE THREAD

**Issue by Sayyiditow** [vincjo/svelte-simple-datatables#10]

**Comment by andreasbhansen** [comment]
@Sayyiditow Did you close this issue because you figured out how to display more than one table on the same page? I'm stuck with a related issue. If I conditionally render one table at the time (always just one `<Datatable>` visible at any given time), it works fine. Once I try to display two tables simultaneously, it crashes -- wonder if it is related to the use of stores. Did you figure out a way around it?
